# Generated by Django 2.0.3 on 2018-03-24 17:07

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20180323_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clayurl',
            name='url',
            field=models.CharField(max_length=220, validators=[shortener.validators.validate_url, shortener.validators.validate_dot_com]),
        ),
    ]
