branch-defaults:
  default:
    environment: null
    group_suffix: null
  master:
    environment: url-shortener
global:
  application_name: url_shortener
  branch: null
  default_ec2_keyname: AWS
  default_platform: Python 3.6
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
