# Generated by Django 2.0.3 on 2018-03-24 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_auto_20180324_1307'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickevent',
            name='clay_url',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='shortener.ClayURL'),
        ),
    ]
