# Generated by Django 2.0.3 on 2018-03-24 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_clickevent_clay_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickevent',
            name='clay_url',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shortener.ClayURL'),
        ),
    ]
